export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: "experience" | "travel" | "continents" | "styles" | "social" | "teacher" | "competition";
  tier: "bronze" | "silver" | "gold" | "platinum" | "diamond";
  requirement: {
    type: string;
    value: number;
  };
}

export const BADGES: Badge[] = [
  // Experience Badges - Earned achievements only!
  {
    id: "dedicated_dancer",
    name: "Dedicated",
    description: "2+ years of dancing experience",
    icon: "🌳",
    category: "experience",
    tier: "bronze",
    requirement: { type: "yearsOfDancing", value: 2 },
  },
  {
    id: "experienced_dancer",
    name: "Experienced",
    description: "4+ years of dancing experience",
    icon: "⭐",
    category: "experience",
    tier: "silver",
    requirement: { type: "yearsOfDancing", value: 4 },
  },
  {
    id: "veteran_dancer",
    name: "Veteran",
    description: "7+ years of dancing experience",
    icon: "🌟",
    category: "experience",
    tier: "gold",
    requirement: { type: "yearsOfDancing", value: 7 },
  },
  {
    id: "legend_dancer",
    name: "Legend",
    description: "10+ years of dancing experience",
    icon: "👑",
    category: "experience",
    tier: "platinum",
    requirement: { type: "yearsOfDancing", value: 10 },
  },
  {
    id: "master_dancer",
    name: "Master",
    description: "20+ years of dancing experience",
    icon: "💎",
    category: "experience",
    tier: "diamond",
    requirement: { type: "yearsOfDancing", value: 20 },
  },

  // City Travel Badges - Must have real travel experience
  {
    id: "city_explorer",
    name: "City Explorer",
    description: "Danced in 3+ cities",
    icon: "🗺️",
    category: "travel",
    tier: "bronze",
    requirement: { type: "citiesVisited", value: 3 },
  },
  {
    id: "globe_trotter_starter",
    name: "Globe Trotter",
    description: "Danced in 5+ cities",
    icon: "🌍",
    category: "travel",
    tier: "silver",
    requirement: { type: "citiesVisited", value: 5 },
  },
  {
    id: "world_dancer",
    name: "World Dancer",
    description: "Danced in 8+ cities",
    icon: "🌏",
    category: "travel",
    tier: "gold",
    requirement: { type: "citiesVisited", value: 8 },
  },
  {
    id: "global_dancer",
    name: "Global Dancer",
    description: "Danced in 12+ cities",
    icon: "🗺️",
    category: "travel",
    tier: "platinum",
    requirement: { type: "citiesVisited", value: 12 },
  },
  {
    id: "nomad",
    name: "Dance Nomad",
    description: "Visited 20+ cities",
    icon: "🌐",
    category: "travel",
    tier: "diamond",
    requirement: { type: "citiesVisited", value: 20 },
  },

  // Continent Travel Badges - Serious travelers only
  {
    id: "continental_explorer",
    name: "Continental Explorer",
    description: "Danced in 2+ continents",
    icon: "🌎",
    category: "continents",
    tier: "bronze",
    requirement: { type: "continentsVisited", value: 2 },
  },
  {
    id: "continental_master",
    name: "Continental Master",
    description: "Danced in 3+ continents",
    icon: "🌍",
    category: "continents",
    tier: "silver",
    requirement: { type: "continentsVisited", value: 3 },
  },
  {
    id: "continental_legend",
    name: "World Citizen",
    description: "Danced in 4+ continents",
    icon: "🗺️",
    category: "continents",
    tier: "gold",
    requirement: { type: "continentsVisited", value: 4 },
  },
  {
    id: "continental_ultimate",
    name: "Global Ambassador",
    description: "Danced in 5+ continents",
    icon: "🌐",
    category: "continents",
    tier: "diamond",
    requirement: { type: "continentsVisited", value: 5 },
  },

  // Dance Style Badges - Multi-style dancers only
  {
    id: "style_versatile",
    name: "Versatile",
    description: "Practicing 2+ dance styles",
    icon: "🕺",
    category: "styles",
    tier: "bronze",
    requirement: { type: "danceStyles", value: 2 },
  },
  {
    id: "style_multitalented",
    name: "Multi-talented",
    description: "Practicing 3+ dance styles",
    icon: "🎭",
    category: "styles",
    tier: "silver",
    requirement: { type: "danceStyles", value: 3 },
  },
  {
    id: "style_polyglot",
    name: "Dance Polyglot",
    description: "Practicing 4+ dance styles",
    icon: "🎪",
    category: "styles",
    tier: "gold",
    requirement: { type: "danceStyles", value: 4 },
  },
  {
    id: "style_omnidancer",
    name: "Omni-Dancer",
    description: "Practicing 6+ dance styles",
    icon: "🌟",
    category: "styles",
    tier: "platinum",
    requirement: { type: "danceStyles", value: 6 },
  },
  {
    id: "style_master",
    name: "Style Master",
    description: "Expert in 2+ dance styles",
    icon: "⭐",
    category: "styles",
    tier: "gold",
    requirement: { type: "expertStyles", value: 2 },
  },
  {
    id: "style_grandmaster",
    name: "Grand Master",
    description: "Expert in 3+ dance styles",
    icon: "🏆",
    category: "styles",
    tier: "diamond",
    requirement: { type: "expertStyles", value: 3 },
  },

  // Social Badges - Build meaningful connections
  {
    id: "social_connector",
    name: "Connector",
    description: "Made 10+ dance friends",
    icon: "🤝",
    category: "social",
    tier: "bronze",
    requirement: { type: "friends", value: 10 },
  },
  {
    id: "social_networker",
    name: "Networker",
    description: "Made 20+ dance friends",
    icon: "💫",
    category: "social",
    tier: "silver",
    requirement: { type: "friends", value: 20 },
  },
  {
    id: "social_builder",
    name: "Community Builder",
    description: "Made 35+ dance friends",
    icon: "🌟",
    category: "social",
    tier: "gold",
    requirement: { type: "friends", value: 35 },
  },
  {
    id: "social_hub",
    name: "Social Hub",
    description: "Made 50+ dance friends",
    icon: "✨",
    category: "social",
    tier: "platinum",
    requirement: { type: "friends", value: 50 },
  },
  {
    id: "popular_profile",
    name: "Popular",
    description: "Received 100+ profile likes",
    icon: "❤️",
    category: "social",
    tier: "silver",
    requirement: { type: "likes", value: 100 },
  },
  {
    id: "viral_profile",
    name: "Viral",
    description: "Received 250+ profile likes",
    icon: "🔥",
    category: "social",
    tier: "gold",
    requirement: { type: "likes", value: 250 },
  },
  {
    id: "celebrity_profile",
    name: "Celebrity",
    description: "Received 500+ profile likes",
    icon: "⭐",
    category: "social",
    tier: "platinum",
    requirement: { type: "likes", value: 500 },
  },
  {
    id: "superstar_profile",
    name: "Superstar",
    description: "Received 1000+ profile likes",
    icon: "✨",
    category: "social",
    tier: "diamond",
    requirement: { type: "likes", value: 1000 },
  },

  // Teacher Badges
  {
    id: "teacher_new",
    name: "New Teacher",
    description: "Started teaching dance",
    icon: "📚",
    category: "teacher",
    tier: "bronze",
    requirement: { type: "isTeacher", value: 1 },
  },
  {
    id: "teacher_experienced",
    name: "Experienced Instructor",
    description: "5 years of teaching experience",
    icon: "🎓",
    category: "teacher",
    tier: "gold",
    requirement: { type: "teachingYears", value: 5 },
  },
  {
    id: "teacher_master",
    name: "Master Teacher",
    description: "10+ years of teaching experience",
    icon: "🏆",
    category: "teacher",
    tier: "diamond",
    requirement: { type: "teachingYears", value: 10 },
  },

  // Jack & Jill Competition Badges
  {
    id: "jj_competitor",
    name: "J&J Competitor",
    description: "Competed in 3+ Jack & Jill competitions",
    icon: "🎲",
    category: "competition",
    tier: "bronze",
    requirement: { type: "jjCompetitions", value: 3 },
  },
  {
    id: "jj_podium",
    name: "Podium Finisher",
    description: "Placed in the top 3 at a J&J competition",
    icon: "🥉",
    category: "competition",
    tier: "silver",
    requirement: { type: "jjPodiumFinishes", value: 1 },
  },
  {
    id: "jj_competitive",
    name: "Competitive Dancer",
    description: "Placed in the top 3 at 3+ J&J competitions",
    icon: "🏅",
    category: "competition",
    tier: "gold",
    requirement: { type: "jjPodiumFinishes", value: 3 },
  },
  {
    id: "jj_champion",
    name: "J&J Champion",
    description: "Won 2+ Jack & Jill competitions",
    icon: "🥇",
    category: "competition",
    tier: "platinum",
    requirement: { type: "jjFirstPlaces", value: 2 },
  },
  {
    id: "jj_master",
    name: "J&J Master",
    description: "Won 5+ Jack & Jill competitions",
    icon: "👑",
    category: "competition",
    tier: "diamond",
    requirement: { type: "jjFirstPlaces", value: 5 },
  },
];

export const TIER_COLORS = {
  bronze: "badge-warning",
  silver: "badge-neutral",
  gold: "badge-warning",
  platinum: "badge-info",
  diamond: "badge-secondary",
};

export const TIER_LABELS = {
  bronze: "Bronze",
  silver: "Silver",
  gold: "Gold",
  platinum: "Platinum",
  diamond: "Diamond",
};

